version: '3'
services:
  web_nginx:
    build: ./nginx
    ports:
      - "8000:80"
      - "443:443"
    volumes:
      # source
      - ./www/:/usr/share/nginx/html/
      - ./nginx/log/:/var/log/nginx/:rw
      - ./nginx/certs/:/etc/ssl/certs/:ro
      - ./nginx/conf/:/etc/nginx/conf.d/:ro
    # links:
    #   - web_php72_fpm
    networks:
        - net-php72-fpm

  web_php72_fpm:
    build: ./php72-fpm
    expose:
      - "9000"
    volumes:
      - ./php72-fpm/php.ini:/usr/local/etc/php/php.ini:ro
      - ./php72-fpm/www.conf:/usr/local/etc/php-fpm.d/www.conf:ro
      - ./www/:/usr/share/nginx/html/
    # links:
    #   - web_redis
    networks:
        - net-php72-fpm
        - net-redis

  web_redis:
    build: ./redis
    ports:
      - "6379:6379"
    volumes:
      # source
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf:ro
    networks:
        - net-redis

networks:
  net-php72-fpm:
  net-redis:
